### PR TITLE
Changed Freezer name from Keshari to Chodera

### PR DESCRIPTION
**Pull request by Lucelenie**
Changed Freezer name from Keshari to Chodera in the index.html file.

### CODE REVIEW

**Comment by jchodera** [comment]
Thanks!

**Comment by sonyahanson** [comment]
@jhprinz Any idea why this didn't work?
keshari_freezer

We changed the name in the `index.html`. There are a few other places where 'keshari' exists in the code, but they seem unlikely to be the culprit:
keshari_search

Also, what is this plate directory?

**Comment by jhprinz** [comment]
Okay, the fix in line 132 should break the code (unfortunately). This is just the code that takes the information from the website and construct a dictionary out of it and one of the variables was named keshari. If you changed it, you need to change the counterpart in the `.js` file in the modules part of the website (in `lab`). The place where you need to change it is in lab/index.html like you did. Of course you need to reload the page (eventually twice) since it could be cached...

**Comment by sonyahanson** [comment]
Oh. You think it's cached?

Yeah, we didn't change line 132, but I think we can figure out how to make sure it doesn't break the code when we do.

**Pull request merged**
